#!/bin/bash

#######################################################
# GENERAL ALIAS'S
#######################################################

# Alias's to modified commands
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm --recursive --interactive --verbose'
alias rmd='rm  --recursive --force --verbose --interactive'
alias mkdir='mkdir -pv'
alias cls='clear'
alias vi='vim'
alias df='df -H'
alias du='du -ch'
alias ping='ping -c 4'

# Change directory aliases
alias ..='cd ..'
alias ...='cd ../..'

# Alias's for multiple directory listing commands
alias ls='ls --color=always'
alias lX='ls -lXBhA'
alias lS='ls -lSrhA'
alias lR='ls -lRhA'
alias lt='ls -ltrhA'

# colored grep
alias grep='grep --color=ALWAYS'

# alias chmod commands
alias mx='chmod a+x'
alias 600='chmod -Rv 600'
alias 644='chmod -Rv 644'
alias 700='chmod -Rv 700'
alias 755='chmod -Rv 755'
alias 777='chmod -Rv 777'

# Search command line history
alias hi='history | grep'

# Search running processes
alias ps='ps auxf'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# resume wget by default
alias wget='wget -c'

# find a file insensitve name
alias ff='find . -type f -iname'